blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/renzojared/DotEmilu/discussions
    about: Ask questions, share ideas, or discuss DotEmilu with the community
